# Generated by Django 5.2.4 on 2025-07-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='discription',
            new_name='description',
        ),
    ]
